# GET http://localhost:3003/api/blogs/

# POST  http://localhost:3003/api/blogs/
# Content-Type: application/json

# {
#     "title": "TestDB2",
#     "author": "SpaceHobo3131",
#     "url": "someurl",
#     "likes": "100500"
# }

# POST  http://localhost:3003/api/blogs/
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlayIsImlkIjoiNjQ1Y2JjNDBjM2Q2MzdmMjFhNzkwNDlmIiwiaWF0IjoxNjgzODAwMTU4fQ.JNISf1C2fPHVr3ELxoZ8gtfeLDO-rxQtz5GQYHuXRIU

# {
#     "title": "kek1st",
#     "author": "kekkek",
#     "url": "kek.com",
#     "likes": "0"
# }

# POST  http://localhost:3003/api/login/
# Content-Type: application/json

# {
#     "username": "kek",
#     "password": "123"
# }
 
# PUT  http://localhost:3003/api/blogs/644bc912b08e88c2724c4425
# Content-Type: application/json

# {
#     "likes": "5"
# }

# POST  http://localhost:3003/api/users/
# Content-Type: application/json

# {
#     "username": "user2",
#     "name": "dat Name",
#     "password": "321"
# }

# DELETE http://localhost:3003/api/blogs/645e57de42f2c81a049ab3d0
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlayIsImlkIjoiNjQ1Y2JjNDBjM2Q2MzdmMjFhNzkwNDlmIiwiaWF0IjoxNjgzODAwMTU4fQ.JNISf1C2fPHVr3ELxoZ8gtfeLDO-rxQtz5GQYHuXRIU

# GET http://localhost:3003/api/blogs/645cbc40c3d637f21a79049f
# Content-Type: application/json


POST http://localhost:3003/api/blogs/645cc0a92d21f4bcb84627fe/comments
Content-Type: application/json

{
    "comment": "kekek"
}
